for i in range(5):
    print("Check")
    print("hello, world!")
    print("hello, world1!")
    print("hello, world!")
    print("hello, world!")
    print("hello123, world!")
    print("hellogala, world!")
    print("hello234567888, world!")
    print("#####")
    print(i + 1)
    print(i + 1)