name: Hello World Workflow

on:
  push:
    branches:
      - master  # Trigger on push to main branch

jobs:
  hello-world-job:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu VM
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Checkout the repository code
        
      - name: Print Hello World
        run: echo "Hello, World!"  # Print Hello World in the Actions log
